version: '3.8'
services:
  postgres:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=owncloud
    volumes:
      - postgres:/var/lib/postgresql/data
      - backups:/backups
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste # Conteiner sobe apenas nos n贸s com esse label

  owncloud:
    depends_on: 
      - postgres
      - redis
    image: owncloud/server
    environment:
      - OWNCLOUD_DOMAIN=ifrr.local
      - OWNCLOUD_DB_TYPE=pgsql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=postgres
      - OWNCLOUD_DB_PASSWORD=postgres
      - OWNCLOUD_DB_HOST=postgres
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    volumes:
      - owncloud:/mnt/data
    ports:
      - 8097:8080
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste # Conteiner sobe apenas nos n贸s com esse label

  redis:
    image: redis:alpine3.12
    environment:
      - REDIS_DATABASES=1
    volumes:
      - redis:/data/owncloud/redis
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste # Conteiner sobe apenas nos n贸s com esse label

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - backups:/backups
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=owncloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=80
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste # Conteiner sobe apenas nos n贸s com esse label

volumes:
  postgres:
    driver_opts:
      o: bind
      type: none
      device: /data/owncloud/postgres
  backups:
    driver_opts:
      o: bind
      type: none
      device: /data/owncloud/backups
  owncloud:
    driver_opts:
      o: bind
      type: none
      device: /data/owncloud/owncloud
  redis:
    driver_opts:
      o: bind
      type: none
      device: /data/owncloud/redis

networks:
  owncloud:
    driver: overlay
